import {
  barcelona1,
  barcelona2,
  barcelona3,
  barcelona4,
  barcelona5,
  barcelona6,
  board1,
  board2,
  centre1,
  centre2,
  centre3,
  centre4,
  lamina1,
  lamina2,
  lamina3,
  lamina4,
  cartama1,
  cartama2,
  cartama3,
  cartama4,
  cartama5,
  cartama6,
  huni1,
  huni2,
  huni3,
  huni4,
  huni5,
  frasca1,
  frasca2,
  frasca3,
  frasca4,
  frasca5,
  frasca6,
} from "../assets";

const proyectos = [
  {
    title: "Barcelona World Basketball Festival",
    path: "barcelona-world-basketball-festival",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: barcelona1,
    images: [barcelona2, barcelona3, barcelona4, barcelona5, barcelona6],
    categoria: "arquitectura",
  },
  {
    title: "Boardriders Barcelona",
    path: "boardriders-barcelona",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: board1,
    images: [board2],
    categoria: "sport",
  },
  {
    title: "Centre de Emprenedoria de la Universitat de Vic",
    path: "centre-emprendedoria-vic",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: centre1,
    images: [centre1, centre2, centre3, centre4],
    categoria: "patrimonio",
  },
  {
    title: "Centro Civico Ca La Mina",
    path: "centro-civico-la-mina",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: lamina1,
    images: [lamina1, lamina2, lamina3, lamina4],
    categoria: "arquitectura",
  },
  {
    title: "Complejo Deportivo de Cartama",
    path: "cartama",
    location: "Malaga - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: cartama1,
    images: [cartama1, cartama2, cartama3, cartama4, cartama5, cartama6],
    categoria: "inmobiliario",
  },
  {
    title: "Habitage Unigamiliar E+L",
    path: "habitage-el",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: huni1,
    images: [huni1, huni2, huni3, huni4, huni5],
    categoria: "arquitectura",
  },
  {
    title: "La Frasca",
    path: "la-frasca",
    location: "Haro - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: frasca1,
    images: [frasca1, frasca2, frasca3, frasca4, frasca5, frasca6],
    categoria: "patrimonio",
  },
];

const colores = {
  todos: "#DF6537",
  arquitectura: "#3068B0",
  sport: "#72BB66",
  patrimonio: "#CA3038",
  inmobiliario: "#DEC800",
};

const espacios = ["sobre nosotros", "noticias", "equipo"];
const spaces = ["about us", "news", "team"];

const partners = [
  { name: "SOFAR", url: "https://espacio-sofar.com/" },
  {
    name: "Frediani Arquitectura",
    url: "http://www.fredianiarquitectura.com/",
  },
  {
    name: "Blancafort-Reus",
    url: "https://www.blancafort-reus.com/",
  },
  {
    name: "Zaha Hadid Architects",
    url: "http://www.zaha-hadid.com/",
  },
  {
    name: "Detalldisseny",
    url: "http://www.detalldisseny.com/",
  },
  {
    name: "Monumenta",
    url: "http://www.monumenta.info/",
  },
  {
    name: "Coco Consulting",
    url: "http://www.cocoideas.com/",
  },
  {
    name: "Grup de Recerca en Innovació Territorial",
    url: "http://www.tecnocampus.cat/ca/recerca/gric",
  },
];

export { proyectos, colores, espacios, partners };
