import {
  barcelona1,
  barcelona2,
  barcelona3,
  barcelona4,
  barcelona5,
  barcelona6,
  board1,
  board2,
  centre1,
  centre2,
  centre3,
  centre4,
  lamina1,
  lamina2,
  lamina3,
  lamina4,
  cartama1,
  cartama2,
  cartama3,
  cartama4,
  cartama5,
  cartama6,
  huni1,
  huni2,
  huni3,
  huni4,
  huni5,
  frasca1,
  frasca2,
  frasca3,
  frasca4,
  frasca5,
  frasca6,
} from "../assets";

// const replace = (title) => {
//   return title.replace(/\s+/g, '-');
// }

export const mockProject = {
  title: "Barcelona World Basketball Festival",
  path:  "barcelona-world-basketball-festival",
  location: "Barcelona - España",
  description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
  año: "2009",
  superficie: "1400 mt2",
  equipo: ["Jorge Leiva", "Mauro Zeta", "Algun Otro"],
  fotografia: "Claudia Shiffer",
  colaboradores: "Amansio Ortega",
  thumb: barcelona1,
  images: [barcelona2, barcelona3, barcelona4, barcelona5, barcelona6],
  categoria: "Arquitectura"
}

const proyectos = [
  {
    title: "Barcelona World Basketball Festival",
    path:  "barcelona-world-basketball-festival",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: barcelona1,
    images: barcelona2, barcelona3, barcelona4, barcelona5, barcelona6,
    categoria: "Arquitectura"
  },
  {
    title: "Boardriders Barcelona",
    path: "boardriders-barcelona",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: board1,
    images: board2,
    categoria: "Sport"
  },
  {
    title: "Centre de Emprenedoria de la Universitat de Vic",
    path: "centre-emprendedoria-vic",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: centre1,
    images: centre1, centre2, centre3, centre4,
    categoria: "Patrimonio"
  },
  {
    title: "Centro Civico Ca La Mina",
    path:"centro-civico-la-mina",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: lamina1,
    images: lamina1,lamina2, lamina3, lamina4,
    categoria: "Arquitectura"
  },
  {
    title: "Complejo Deportivo de Cartama",
    path: "cartama",
    location: "Malaga - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: cartama1,
    images: cartama1,cartama2,cartama3,cartama4,cartama5,cartama6,
    categoria: "Inmobiliario"
  },
{
    title: "Habitage Unigamiliar E+L",
    path: "habitage-el",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: huni1,
    images: huni1,huni2,huni3, huni4,huni5,
    categoria: "Arquitectura"
},
{
    title: "La Frasca",
    path: "la-frasca",
    location: "Haro - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: frasca1,
    images: frasca1, frasca2, frasca3, frasca4, frasca5, frasca6,
    categoria: "Patrimonio"
},
//hasta aca!
{
    title: "Barcelona World Basketball Festival",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: barcelona1,
    images: barcelona1, barcelona2, barcelona3, barcelona4, barcelona5, barcelona6,
    categoria: "Arquitectura"
  },
  {
    title: "Boardriders Barcelona",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: board1,
    images: board1, board2,
    categoria: "Sport"
  },
  {
    title: "Centre de Emprenedoria de la Universitat de Vic",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: centre1,
    images: centre1, centre2, centre3, centre4,
    categoria: "Patrimonio"
  },
  {
    title: "Centro Civico Ca La Mina",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: lamina1,
    images: lamina1,lamina2, lamina3, lamina4,
    categoria: "Arquitectura"
  },
  {
    title: "Complejo Deportivo de Cartama",
    location: "Malaga - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: cartama1,
    images: cartama1,cartama2,cartama3,cartama4,cartama5,cartama6,
    categoria: "Inmobiliario"
  },
{
    title: "Habitage Unigamiliar E+L",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: huni1,
    images: huni1,huni2,huni3, huni4,huni5,
    categoria: "Arquitectura"
},
{
    title: "La Frasca",
    location: "Haro - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: frasca1,
    images: frasca1, frasca2, frasca3, frasca4, frasca5, frasca6,
    categoria: "Patrimonio"
},
{
    title: "Barcelona World Basketball Festival",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: barcelona1,
    images: barcelona1, barcelona2, barcelona3, barcelona4, barcelona5, barcelona6,
    categoria: "Arquitectura"
  },
  {
    title: "Boardriders Barcelona",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: board1,
    images: board1, board2,
    categoria: "Sport"
  },
  {
    title: "Centre de Emprenedoria de la Universitat de Vic",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: centre1,
    images: centre1, centre2, centre3, centre4,
    categoria: "Patrimonio"
  },
  {
    title: "Centro Civico Ca La Mina",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: lamina1,
    images: lamina1,lamina2, lamina3, lamina4,
    categoria: "Arquitectura"
  },
  {
    title: "Complejo Deportivo de Cartama",
    location: "Malaga - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: cartama1,
    images: cartama1,cartama2,cartama3,cartama4,cartama5,cartama6,
    categoria: "Inmobiliario"
  },
{
    title: "Habitage Unigamiliar E+L",
    location: "Barcelona - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: huni1,
    images: huni1,huni2,huni3, huni4,huni5,
    categoria: "Arquitectura"
},
{
    title: "La Frasca",
    location: "Haro - España",
    description: "",
    año: "",
    superficie: "",
    equipo: "",
    fotografia: "",
    colaboradores: "",
    thumb: frasca1,
    images: frasca1, frasca2, frasca3, frasca4, frasca5, frasca6,
    categoria: "Patrimonio"
},
];


export { proyectos };