import {
  mirasol1,
  mirasol2,
  mirasol3,
  sws1,
  sws2,
  sws3,
  fluidra1,
  fluidra2,
  fluidra3,
  fluidra4,
  fluidra5,
  lalanne1,
  lalanne10,
  lalanne2,
  lalanne3,
  lalanne4,
  lalanne5,
  lalanne6,
  lalanne7,
  lalanne8,
  lalanne9,
  hp831,
  hp832,
  hp833,
  hp834,
  hp835,
  hp836,
  hp837,
  gran1,
  gran2,
  gran3,
  terrassa1,
  terrassa2,
  terrassa3,
  terrassa4,
  hp8111,
  hp8112,
  hp8113,
  hp8131,
  hp8132,
  hp8133,
  hp8134,
  hp8135,
  artrux1,
  artrux2,
  artrux3,
  artrux4,
  artrux5,
  hu0051,
  hu0052,
  hu0053,
  hu0054,
  hu0055,
  hu0056,
  hu081,
  hu082,
  hu083,
  hu084,
  hu085,
  gcz1,
  gcz2,
  gcz3,
  gcz4,
  gcz5,
  blh1,
  blh2,
  blh3,
  blh4,
  blh5,
  blh6,
  blh7,
  im561,
  im562,
  im563,
  hu831,
  hu832,
  vts1,
  vts2,
  vts3,
  vts4,
  vts5,
  vts6,
  vts7,
  ccev1,
  ccev2,
  ccev3,
  iscola1,
  iscola2,
  ondara1,
  ondara2,
  hp1,
  water1,
  water2,
  water3,
  water4,
  water5,
  water6,
  iglesia1,
  iglesia2,
  iglesia3,
  iglesia4,
  iglesia5,
  iglesia6,
  wbf1,
  wbf2,
  wbf3,
  wbf4,
  wbf5,
  nova1,
  nova2,
  corus1,
  corus2,
  corus3,
  corus4,
  corus5,
  corus6,
  can1,
  can2,
  can3,
  can4,
  hu6491,
  hu6492,
  hu6493,
  hu6494,
  hu6495,
  cugat1,
  cugat2,
  cugat3,
  cugat4,
  cugat5,
  cugat6,
  cugat7,
  boardriders1,
  boardriders2,
  boardriders3,
  boardriders4,
  boardriders5,
  cartama1,
  cartama2,
  cartama3,
  cartama4,
  cartama5,
  cartama6,
  mina1,
  mina2,
  mina3,
  mina4,
  sm1,
  sm2,
  sm3,
  sm4,
  campus1,
  campus10,
  campus11,
  campus2,
  campus3,
  campus4,
  campus5,
  campus6,
  campus7,
  campus8,
  campus9,
  oasis1,
  oasis2,
  oasis3,
  oasis4,
  olot1,
  olot2,
  olot3,
  sws4,
} from "../assets";

const proyectosES = [
  {
    ref: "DA0005",
    short: "VLLV",
    title: "HU005",
    categoria: "inmobiliario",
    location: "Vallvidrera - Barcelona",
    superficie: 295,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 6,
    año: 2000,
    images: [hu0051, hu0052, hu0053, hu0054, hu0055, hu0056],
    description:
      "Vivienda unifamiliar de nueva planta en el entorno urbano de Barcelona.  Optimización de los recursos del emplazamiento mediante la creación de patios interiores y exteriores que mejoran la privacidad y la iluminación natural de la vivienda.",
  },
  {
    ref: "DA0008",
    short: "",
    title: "HU008",
    categoria: "inmobiliario",
    location: "Matadepera - Barcelona",
    superficie: 235,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 7,
    año: 2000,
    images: [hu081, hu082, hu083, hu084, hu085],
    description:
      "Vivienda unifamiliar en el límite del suelo urbano y frente a un espacio de alto valor ecológico.  El proyecto compacta la edificabilidad liberando la mayoría de la parcela y desdibuja el volumen, reduciendo la lectura de su altura y presencia.  La vivienda es luminosa, en relación directa con el espacio natural que la rodea.",
  },
  {
    ref: "DA0056",
    short: "IM0056",
    title: "IM0056",
    categoria: "inmobiliario",
    location: "Sant Feliu de Llobregat - Barcelona",
    superficie: 855,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 4,
    año: 2005,
    images: [im561, im562, im563],
    description:
      "Edificio logístico y de oficinas. Construcción modular y prefabricada mejorando su puesta en obra. Las oficinas en la fachada principal se integran en el material de cerramiento, quedando protegidas por un brisesoleil metálico que permite una escala industrial en los materiales y soluciones domésticas para el usuario.",
  },
  {
    ref: "DA0083",
    short: "IH0083",
    title: "IH0083",
    categoria: "inmobiliario",
    location: "Barcelona",
    superficie: 185,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [hu831, hu832],
    description: "",
  },
  {
    ref: "DA0309",
    short: "ISCOLA",
    title: "Edificio Iscola",
    categoria: "inmobiliario",
    location: "Benicarló (Castelló)",
    superficie: 19850,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [iscola1, iscola2],
    description:
      "Edificio plurifamiliar de 112 viviendas, zonas comunes, locales comerciales y aparcamientos.",
  },
  {
    ref: "DA0312",
    short: "ONDARA",
    title: "Edificio Ondara",
    categoria: "inmobiliario",
    location: "Tàrrega (Lleida)",
    superficie: 6182,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 8,
    año: null,
    images: [ondara1, ondara2],
    description:
      "Edificio plurifamiliar de 41 viviendas, zonas comunes, local comercial y aparcamientos.",
  },
  {
    ref: "DA0322",
    short: "HP0322",
    title: "HP0322",
    categoria: "inmobiliario",
    location: "Barcelona",
    superficie: 1188,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [hp1],
    description:
      "Edificio plurifamiliar entre medianeras de 12 viviendas en Barcelona.",
  },
  {
    ref: "DA369",
    short: "C. NOVA",
    title: "Edifici Ciutat Nova",
    categoria: "inmobiliario",
    location: "Benicarló (Castelló)",
    superficie: 3945,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [nova1, nova2],
    description:
      "Edificio plurifamiliar de 47 viviendas, zonas comunes, local comercial y aparcamientos.",
  },
  {
    ref: "DA0649",
    short: "HU0649",
    title: "HU0649",
    categoria: "inmobiliario",
    location: "",
    superficie: null,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [hu6491, hu6492, hu6493, hu6494, hu6495],
    description:
      "Vivienda unifamiliar en Valldoreix ( Barcelona). El proyecto maximiza los espacios relacionales entre tres núcleos compactos de mayor intimidad. El comedor, sala de estar y el estudio profesional se abren a la vegetación circundante con visuales diagonales, incorporando el espacio al interior. Las alturas de los espacios, su compacidad o su transparencia proponen distintas maneras de vivirlos, pero sólo les da sentido el uso que de ellos hace la familia que los habita. Compartir un desayuno con ellos da sentido final a todo el proyecto y convierte la materia en sentimientos.",
  },
  {
    ref: "DA0803",
    short: "HP0803",
    title: "HP0803",
    categoria: "inmobiliario",
    location: "Barcelona",
    superficie: 85,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Berkshire Hathaway"],
    fotografia: "",
    orden: 5,
    año: 2022,
    images: [hp831, hp832, hp833, hp834, hp835, hp836, hp837],
    description:
      "División y segregación de un inmueble en dos nuevas viviendas. Estudio de alternativas de proyecto, renovación energética y selección gestión de proyecto y obras.",
  },
  {
    ref: "DA0811",
    short: "HP0811",
    title: "HP0811",
    categoria: "inmobiliario",
    location: "Sant Cugat del Vallès ( Barcelona)",
    superficie: 1399,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 4,
    año: null,
    images: [hp8111, hp8112, hp8113],
    description:
      "Edificio plurifamiliar de 9 viviendas, zonas comunes, local comercial y aparcamientos.",
  },
  {
    ref: "DA0813",
    short: "HP0813",
    title: "HP0813",
    categoria: "inmobiliario",
    location: "Barcelona",
    superficie: 225,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Berkshire Hathaway"],
    fotografia: "",
    orden: 5,
    año: 2023,
    images: [hp8131, hp8132, hp8133, hp8135, hp8134],
    description:
      "Reforma de vivienda en Barcelona. Estudio de alternativas de proyecto, renovación energética y selección gestión de proyecto y obras.",
  },

  {
    ref: "DA0010",
    short: "GCZ",
    title: "Gran Cafe Zaragoza",
    categoria: "patrimonio",
    location: "Zaragoza",
    superficie: 180,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Carmen Sisquella"],
    fotografia: "",
    orden: 4,
    año: 2000,
    images: [gcz1, gcz2, gcz3, gcz4, gcz5],
    description:
      "Reforma del emblemático establecimiento de la calle Alfonso I de Zaragoza obra del arquitecto local Luís Aladrén en 1885, con un estilo ecléctico e historicista propio de finales del s. XIX. El comercio original con una gran fachada en esquina se destinó a una afamada joyería para la nueva burguesía de la ciudad. Los expositores acristalados y los techos artesonados del interior transmitían el lujo que ostentaba el comercio de plata y joyas. El proyecto transformó el uso comercial al de la nueva propiedad “Gran Café Zaragoza”  que más tarde se mantendría como “Café 1885”. Las salas interiores se limpian de cortinajes, dando una mayor protagonismo a las columnas de fundición y los trabajados techos artesonados. Local declarado  Bien Catalogado del Patrimonio Cultural Aragonés por el Gobierno de Aragón desde 2002.",
  },
  {
    ref: "DA0569",
    short: "STA MARIA",
    title: "Santa Maria 33",
    categoria: "patrimonio",
    location: "Sant Cugat del Vallès ( Barcelona)",
    superficie: 165,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Carmen Sisquella"],
    fotografia: "",
    orden: 3,
    año: 2017,
    images: [sm1, sm2, sm3, sm4],
    description:
      "Actuación en una pequeña edificación de valor histórico en el núcleo antiguo de Sant Cugat del Vallés.  La vivienda tradicional abandonada se actualiza al nuevo uso  en la principal calle comercial del municipio, manteniendo el uso de vivienda en la planta primera. Se recuperan y valorizan la fachada principal, la tradicional estructura de “volta”  y  los aleros de cubierta. También se tratan y eliminan las humedades de capilaridad y el ataque a la estructura de cubierta por termitas y humedades. Edificio declarado BCIL ( Bien Cultural de Interés local)",
  },
  {
    ref: "DA0573",
    short: "UVIC-CAMPUS",
    title: "Uvic Campus Casa Convalescencia",
    categoria: "patrimonio",
    location: "Vic ( Barcelona)",
    superficie: 4050,
    promotor: "Universitat de Vic",
    equipo: ["D'Aura Arquitectura", "Vives-Bassa-Ayala SCP"],
    fotografia: "",
    orden: 2,
    año: null,
    images: [
      campus1,
      campus10,
      campus11,
      campus2,
      campus3,
      campus4,
      campus5,
      campus6,
      campus7,
      campus8,
      campus9,
    ],
    description:
      "Restauración de la antigua Casa de Convalecencia del Hospital de la Santa Creu de Vic, obra del arquitecto Josep Morató i Codina, construido a caballo entre el barroco(s. finales XVIII) y el neoclasicismo (principios.XIX). Se trata de una actuación en 4000 m2 de edificio, incluyendo, situado en el límite de la antigua muralla medieval de Vic. El objetivo de la actuación es reutilizar el edificio como sede del Rectorado de la Universidad de Vic y un centro de expendeduría y co-working, Creacció. En el proceso han estado involucradas la Universidad de Vic, El Ayuntamiento de Vic  y el Patronato del Hospital de la Santa Creu , como propietario del edificio, durante los casi 14 años que ha durado la intervención completa. El edificio estaba en mal estado de conservación, pero presentaba una riqueza constructiva y unos espacios arquitectónicos de mucha calidad, incluyendo un claustro neoclásico, 24 bóvedas barrocas y pinturas de gran calidad. Se ha recuperado el claustro y todas las circulaciones alrededor de este. El espíritu restaurador nos ha llevado a recuperar o reparar las carpinterías existentes bien conservadas, mejorando el comportamiento térmico. Se han conservado también, reparando o reforzando la mayor parte de las estructuras de madera y las 24 bóvedas existentes. Después de la Restauración el Edificio ha sido declarado BCIL ( Bien Cultural de Interés local)",
  },
  {
    ref: "DA0621",
    short: "PARANINF",
    title: "Antigua Esglesia de la Santa Creu de Vic y Sala Gótica-Paraninf",
    categoria: "patrimonio",
    location: "Vic ( Barcelona)",
    superficie: 4050,
    promotor: "Universitat de Vic",
    equipo: ["D'Aura Arquitectura", "Vives-Bassa-Ayala SCP"],
    fotografia: "",
    orden: 1,
    año: null,
    images: [iglesia1, iglesia2, iglesia3, iglesia4, iglesia5, iglesia6],
    description:
      "La Iglesia de la Santa Creu, obra de Josep Morató i Sellés, se construyó entre 1748 y 1753. Es una nave única de imponente volumetría arquitectónica, destacando especialmente el cambril, espléndidamente ornamentado. La decoración pictórica interior ha sido restaurada en diferentes etapas históricas, con mayor y menor fortuna, quedando finalmente un estilo recargado. Todo el conjunto arquitectónico es barroco y de transición neoclásica. Se restaura e incorpora al uso de paraninfo una sala adosada a la iglesia de origen gótico con grandes arcos ojivales perteneciente en origen al Hospital de la Santa Creu. Esta restauración integral ha permitido recuperar y poner en valor la obra de toda una saga de artistas y maestros de obra importantísimos de un periodo histórico en Cataluña, entre los siglos S.XVII-XVIII: la nisaga vigatana de los Morató. Edificio declarado BCIL ( Bien Cultural de Interés local)",
  },
  {
    ref: "DA0722",
    short: "FJB",
    title: "Casa Francesc Lalanne",
    categoria: "patrimonio",
    location: "Barcelona",
    superficie: null,
    promotor: "Fundació Jaume Bofill",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "",
    orden: 3,
    año: null,
    images: [
      lalanne1,
      lalanne2,
      lalanne3,
      lalanne4,
      lalanne5,
      lalanne6,
      lalanne7,
      lalanne8,
      lalanne9,
      lalanne10,
    ],
    description:
      "Conjunto de actuaciones en la Casa Francesc Lalanne, también conocidas como Casas Armentera i Parellada, del Eixample de Barcelona. Se interviene en este edificio de  1908-1910, recuperando elementos históricos ocultos por intervenciones previas, realizando un detallado análisis estructural, y adaptando los espacios a nuevas necesidades de la Fundación propietaria del edificio.  La valorización de las bóvedas tabicadas y los pavimentos de Nolla ponen en contexto la edificación proyectada por el arquitecto de l s. XIX-XX Arnau Calvet. 1er Premio Concurso de proyectos. Edificio declarado BCIL (Bien Cultural de Interés local)",
  },
  {
    ref: "DA0804",
    short: "ARTRUTX",
    title: "Talaia D'Artrutx",
    categoria: "patrimonio",
    location: "Ciutadella de Menorca ( Balears)",
    superficie: 115,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 5,
    año: null,
    images: [artrux1, artrux2, artrux3, artrux4, artrux5],
    description:
      "Las “Talaias” son interesantes torres de observación ubicadas estratégicamente alrededor de la costa menorquina. La Talaia de Artruts está ubicada en la costa sudoeste de Menorca y fechada entre finales del siglo XVI iy principios del XVII. Es un Bien de Interés Cultural (BIC) identificado en el Catálogo de protección del Patrimonio Histórico de Ciutadella. El proyecto consolida la edificación con materiales locales y tradicionales y recupera elementos eliminados. La actuación permitirá evitar el deterioro progresivo y la futura visita del edificio.",
  },
  {
    ref: "DA0015",
    short: "LA FRASCA",
    title: "Bodega R. Lopez de Heredia",
    categoria: "arquitectura",
    location: "Haro (La Rioja)",
    superficie: 680,
    promotor: "R. López de Heredia",
    equipo: ["D'Aura Aquitectura", "Zaha Hadid Architects", "IOA Arquitectura"],
    fotografia: "",
    orden: 2,
    año: 2006,
    images: [blh1, blh2, blh3, blh4, blh5, blh6, blh7],
    description:
      "Salas de cata, patio de recepciones y edificio de atención al visitante en Bodegas R. López de Heredia. Como arquitectos locales, en colaboración con Zaha Hadid Arch., hemos experimentado con el diseño de espacios arquitectónicos, soluciones estructurales innovadoras y nuevos materiales, que sirven como referencia para la renovación de una bodega familiar centenaria. El resultado ha añadido nuevos valores relativos a la cultura tradicional de 'Viña Tondonia'. El edificio de recepción, alberga en su interior el pabellón de muestras que Viña Tondonia mostró en la feria de 1910. El nuevo contenedor modular fue inicialmente concebido para participar en nuevas ferias, y, finalmente, se erige como un punto de acceso para los visitantes de la bodega. Tanto 'La Frasca', como los espacios exteriores, el nuevo acceso a la bodega o de las salas de degustación incorporan soluciones tecnológicamente innovadoras para proporcionar al visitante con un nueva aproximación a la bodega, la experiencia del vino y sus paisajes.",
  },
  {
    ref: "DA0118",
    short: "VTDN",
    title: "Viña Tondonia Stand",
    categoria: "arquitectura",
    location: "Barcelona",
    superficie: 680,
    promotor: "R. López de Heredia",
    equipo: ["D'Aura Aquitectura", "IOA Arquitectura"],
    fotografia: "Marcela Grassi",
    orden: 4,
    año: null,
    images: [vts1, vts2, vts3, vts4, vts5, vts6, vts7],
    description:
      "Arquitectura efímera para la imagen de marca de la Bodega en  eventos internacionales. El proyecto de reducidas dimensiones incluye la exhibición de la marca, sus productos, y espacio para la atención a visitantes y degustación de productos. La imagen gráfica de la bodega centenaria y el característico color oro viejo de su vino Gran Reserva adquieren todo el protagonismo en un stand íntimo y singular. Las formas orgánicas acompañan al visitante hacia los viñedos de la Rioja Alta y las galerías subterráneas junto al río Ebro.",
  },
  {
    ref: "DA0138",
    short: "VIENESOS",
    title: "Centre Cívic els Vienesos",
    categoria: "arquitectura",
    location: "El Masnou (Barcelona)",
    superficie: null,
    promotor: "Ajuntament El Masnou",
    equipo: ["D'Aura Aquitectura", "IOA Arquitectura"],
    fotografia: "",
    orden: 6,
    año: null,
    images: [ccev1, ccev2, ccev3],
    description:
      "Ampliación del Centro Cívico  “Els Vienesos” con nuevas salas multiuso, aularios y una nueva planta. El proyecto unifica los espacios existentes y los fruto de la ampliación, dando una nueva fachada urbana y significativa al espacio peatonal contiguo.",
  },
  {
    ref: "DA0470",
    short: "CA LA MINA",
    title: "Centre Cívic CA La Mina",
    categoria: "arquitectura",
    location: "Montcada i Rexac (Barcelona)",
    superficie: 1200,
    promotor: "Ajuntament Montcada i Rexac",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 7,
    año: null,
    images: [mina1, mina2, mina3, mina4],
    description:
      "Ampliación del Centro Cívico del “Parc de les Aigües”.El objetivo principal de este proyecto era encontrar una manera creativa y eficiente para ampliar el centro cívico existente. Este Centro está construido sobre la histórica mina de agua de Montcada i Reixac, que alimenta el 'Rec Comtal' a partir de una vía de agua romana paralela al río Besós. Por tanto, el proyecto tenía que crecer verticalmente y se resolvió con la creación de un nuevo piso sobre el techo existente, que abrió visualmente el edificio hasta el entorno natural que lo rodea. Se propone también una nueva entrada desde la parte posterior del edificio, la calle que conecta Montcada centro con el barrio de Can Sant Joan. La ampliación fue construida con componentes ligeros prefabricados que conectan el edificio existente con la nueva edificación.",
  },
  {
    ref: "DA0523",
    short: "BOARDRIDERS",
    title: "Boardriders Barceloneta",
    categoria: "arquitectura",
    location: "Barcelona",
    superficie: 290,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "",
    orden: null,
    año: null,
    images: [
      boardriders1,
      boardriders2,
      boardriders3,
      boardriders4,
      boardriders5,
    ],
    description:
      "Reconversión de un edificio industrial en el frente marítimo de Barcelona.La transformación de un antiguo espacio industrial y su apertura al nuevo frente marítimo  propició la aparición de espacios disfuncionales y sin encaje urbano. La intervención en estos espacios ha de permitir la llegada de nuevos usos, su actualización, y una nueva integración en el espacio urbano transformado.  Con estas premisas el proyecto mantiene el carácter de los espacios existentes, recuperando estructuras y materiales, pero incorporando las actividades urbanas de ocio y comercio que han colonizado la fachada marítima.",
  },
  {
    ref: "DA0628",
    short: "CORUS",
    title: "Corus Laboratories",
    categoria: "arquitectura",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: 685,
    promotor: "Corus Dental Institute",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "Marcela Grassi",
    orden: 2,
    año: null,
    images: [corus1, corus2, corus3, corus4, corus5, corus6],
    description:
      "Heaquarters y laboratorios de multinacional sanitaria en España. Los procesos productivos de los nuevos laboratorios son el motivo principal del proyecto. Se utilizan diferentes grados de transparencia en la sectorización de los espacios para mostrar y relacionar actividades. La circulación de materiales e informaciones definen distribuciones, materiales y espacios comunes. El trabajo con los diferentes departamentos de la empresa hacen que el edifico sea también imagen corporativa y posicionamiento en su sector.",
  },
  {
    ref: "DA0681",
    short: "BIB SCG",
    title: "Biblioteca Central Sant Cugat",
    categoria: "arquitectura",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: null,
    promotor: "Ajuntament de Sant Cugat",
    equipo: ["D'Aura Arquitectura", "Arturo Frediani"],
    fotografia: "",
    orden: 2,
    año: 2017,
    images: [cugat1, cugat2, cugat3, cugat4, cugat5, cugat6, cugat7],
    description:
      "Nuevo edificio de la Biblioteca Gabriel Ferrater en el parque Ramon Barnils de Sant Cugat del Vallès. 3er premio concurso de proyectos. El proyecto emerge del paisaje como una vieja fortaleza atemporal y sin nombre. Imaginamos la biblioteca como un refugio envolvente de libros, un edificio lleno de rincones luminosos, solitarios o colectivos, donde encontrar la tanto calma de la lectura como el estímulo del encuentro e intercambio de ideas. Los espacios interiores no son rectangulares, sino polígonos de 5 o 6 lados. Así con las estanterías podemos crear espacios que rodeen al lector sin restringir sus movimientos, y aumentando hasta un  50% la capacidad de almacenaje.El  parque forma parte del edificio y el edificio del parque, relacionado los espacios interiores y exteriores. Las cubiertas se confunden visualmente con el parque y por su escalonamiento dejan ver la vista lejana del Monasterio de Sant Cugat, tan presente en el municipio, y con quien la biblioteca guardará una resonancia formal y conceptual. Contemporáneo es compatible con Histórico.",
  },
  {
    ref: "DA0729",
    short: "OASIS",
    title: "Hotel Oasis",
    categoria: "arquitectura",
    location: "Marbella (Málaga)",
    superficie: 650,
    promotor: "Selenta Group",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: 2020,
    images: [oasis1, oasis2, oasis3, oasis4],
    description:
      "Zona de aguas y lounge bar para el Hotel Oasis (Marbella).  Los materiales naturales y la vegetación caracterizan el proyecto para crear un espacio relajante y diferenciado del resto de las actividades del hotel.  La piscina es un espacio social junto al lounge bar que se abre o cierra a ella según los horarios y actividades programadas. El agua es un elemento más del proyecto paisajístico del jardín, incorporando la naturaleza próxima y la más lejana de la Sierra Blanca.",
  },
  {
    ref: "DA0603",
    short: "WBF",
    title: "World Basket Festival",
    categoria: "deporte",
    location: "Barcelona",
    superficie: 2500,
    promotor: "Nike",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 3,
    año: null,
    images: [wbf1, wbf2, wbf3, wbf4, wbf5],
    description:
      "Instalación deportiva con motivo del Mundial de Baloncesto de Barcelona.Más allá de la competición profesional de un Mundial de Baloncesto,  el deporte urbano es una actividad de ocio y socialización.  Esta instalación combina espacios de actividad física y competición, con espectáculos deportivos, musicales, y zonas de ocio. Pese a su breve duración temporal, su impacto urbano ha atraído más de 30.000 visitantes. Todos los elementos de la instalación son de construcción ligera y reutilizables para nuevos eventos.",
  },
  {
    ref: "DA0691",
    short: "WP'18",
    title: "Waterpolo BCN'18 Campeonato de Europa",
    categoria: "deporte",
    location: "Barcelona",
    superficie: 2480,
    promotor: "Federeació Catalana de Natació",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [water1, water2, water3, water4, water5, water6],
    description:
      "Reforma de las piscinas Bernat Picornell para albergar el 33º Campeonato de Europa de Waterpolo Barcelona2018. Se proyecta un nuevo espacio de piscina descubierta, configurando gradas para 3.700 espectadores, una gran pérgola, escenario y pantallas de proyección alrededor de la lámina de agua para crear un espacio único y memorable para este evento deportivo. Se reforma y redistribuyen los vestuarios y espacios anexos de para albergar los equipos deportivos, los técnicos de  gestión de competición y televisiones. Los espacios exteriores se adaptan para acoger el Village, espacios de público y la imagen exterior del evento.",
  },
  {
    ref: "DA0695",
    short: "C.N. OLOT",
    title: "C.N. OLOT",
    categoria: "deporte",
    location: "Olot (Girona)",
    superficie: 3200,
    promotor: "C.N. Olot",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [olot1, olot2, olot3],
    description:
      "Proyecto de rehabilitación y ampliación de las instalaciones deportivas del Club Natació Olot. La intervención sobre el equipamiento existente preserva los espacios funcionales y crea un nuevo cerramiento y estructura de cubierta para la piscina principal. Los espacios exteriores se relacionan con la actividad interior, permitiendo un uso más permeable en verano.",
  },
  {
    ref: "DA0714",
    short: "MIRASOL",
    title: "Piscina Municipal Mirasol",
    categoria: "deporte",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: null,
    promotor: "Ajuntament Sant Cugat",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [mirasol1, mirasol2, mirasol3],
    description:
      "El edificio se sitúa en la parcela destinada, buscando un fácil y natural asentamiento sobre el terreno y despega ligeramente para conectar su alrededor. Se pretende crear un volumen atractivo y compacto que se integre con la edificación y el entorno próximo.La propuesta diferencia los espacios de práctica deportiva, sala de piscina y demás dependencias, otorgando a aquellos un carácter preferente y representativo. El resto de espacios se organizan ordenados en franjas o paquetes longitudinales de programa, coherentes con los esquemas de circulación propios de las instalaciones deportivas 3er premio Concurso de Proyectos.",
  },
  {
    ref: "DA0720",
    short: "FWS-21",
    title: "Fina Artistic Swimming World Series 2021",
    categoria: "deporte",
    location: "Barcelona",
    superficie: 1500,
    promotor: "Federació Catalana Natació/ R/F Espanyola de Natació",
    equipo: [],
    fotografia: "",
    orden: 8,
    año: null,
    images: [sws1, sws2, sws3, sws4],
    description:
      "Arquitectura efímera para la celebración en Barcelona del World Series 2021 de Natación Artística y el Torneo de clasificación Olímpica para Tokio 2021Transformación del equipamiento deportivo para adecuarlo a las necesidades normativas de la competición y a las arquitectónicas de los espectadores y las retransmisiones del espectáculo. Estudio de los ambientes, iluminación y distintos usos de la lámina de agua y escenarios adyacentes para crear una imagen global reconocible al espectador.",
  },
  {
    ref: "DA0733",
    short: "50'S",
    title: "Fluidra 50'S Anniversary",
    categoria: "deporte",
    location: "Barcelona",
    superficie: 1500,
    promotor: "Fluidra",
    equipo: ["D'Aura Arquitectura", "Franc Aleu", "Fluidra Engineering"],
    fotografia: "",
    orden: 6,
    año: null,
    images: [fluidra1, fluidra2, fluidra3, fluidra4, fluidra5],
    description:
      "Proyecto de investigación con un maravilloso equipo para la creación de un espectáculo audiovisual dentro del agua. El espectáculo con una potente narrativa audiovisual se desarrolla sobre y bajo la superficie del agua, utilizando este elemento con su máxima expresividad, gracias al uso de fuentes, plataformas e iluminación que potencian la coreografía de nadadoras y bailarinas. Creación de nuevos elementos técnicos como la plataforma central usada como escenario y proyector de agua, luz y sonido.",
  },
  {
    ref: "DA0745",
    short: "CNT",
    title: "Club Natació Terrassa",
    categoria: "deporte",
    location: "Terrassa (Barcelona)",
    superficie: 3220,
    promotor: "Club Natació Terrassa",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [terrassa1, terrassa2, terrassa3, terrassa4],
    description:
      "Piscina de entrenamiento y competición en el Club Natació Terrassa.El proyecto dota a la instalación de una nueva piscina para actividades deportivas, convertible en dos piscinas de competición de waterpolo mediante un puente móvil. La nueva construcción se inserta entre las existentes, proponiendo una solución compacta y eficiente. El volumen rememora el pasado industrial de la zona pero con la ligereza de los actuales sistemas constructivos prefabricados.  La luz natural y el control de las vistas definen la proporción de huecos y espacios, y la relación con el resto de volúmenes.",
  },
  {
    ref: "DA0758",
    short: "CNG",
    title: "Club Natació Granollers",
    categoria: "deporte",
    location: "Granollers (Barcelona)",
    superficie: 3590,
    promotor: "Ajuntament Granollers",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [gran1, gran2, gran3],
    description:
      "Piscina de entrenamiento y competición en el Club Natació Terrassa. El proyecto dota a la instalación de una nueva piscina para actividades deportivas, convertible en dos piscinas de competición de waterpolo mediante un puente móvil. La nueva construcción se inserta entre las existentes, proponiendo una solución compacta y eficiente. El volumen rememora el pasado industrial de la zona pero con la ligereza de los actuales sistemas constructivos prefabricados.  La luz natural y el control de las vistas definen la proporción de huecos y espacios, y la relación con el resto de volúmenes.",
  },
  {
    ref: "DA0759",
    short: "CARTAMA",
    title: "Complejo Acuático de la Ciudad Deportiva de Cártama",
    categoria: "deporte",
    location: "Cártama (Málaga)",
    superficie: null,
    promotor: "Ayuntamiento de Cártama",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [cartama1, cartama2, cartama3, cartama4, cartama5, cartama6],
    description:
      "Equipamiento deportivo con  piscina cubierta y espacios polivalentes anexos. 1er Premio Concurso de Proyectos.El proyecto propone una instalación que defiende la escala urbana del complejo. El espacio deportivo como infraestructura que en este caso articula la conexión entre los dos núcleos urbanos del municipio. A una escala intermedia, el edificio de zona de aguas interviene en la organización de la Ciudad Deportiva redefiniendo los accesos y la centralidad de los espacios. En la menor escala, el proyecto propone un edificio compacto y de alta eficiencia energética; orientado al usuario y a una gestión sostenible.",
  },
  {
    ref: "DA0802",
    short: "CAN RABASSA",
    title: "Piscina Municipal Can Rabassa",
    categoria: "deporte",
    location: "Vilanova del Vallès (Barcelona)",
    superficie: 1200,
    promotor: "Ajuntament Vilanova del Vallès",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [can1, can2, can3, can4],
    description:
      "Equipamiento municipal deportivo y de ocio. 1er premio concurso.El nuevo complejo de ocio y deporte se ubica junto a la Masía Can Rabassa, mejorando sus prestaciones y poniendo en valor su historia y los espacios naturales circundantes. Redacción de un Plan director del complejo previendo futuros crecimientos y ampliación de actividades, así como su conexión con el Parque Natural de la Serralada Litoral. El equipamiento consta de una piscina mixta (ocio /enseñanza), zonas naturales y de ocio, y un edifico ligero de servicios.",
  },
];

const coloresEs = {
  todos: "#DF6537",
  arquitectura: "#203457",
  deporte: "#7F9052",
  patrimonio: "#7F403B",
  inmobiliario: "#CBA971",
};


export { proyectosES, coloresEs };
