import {
  mirasol1,
  mirasol2,
  mirasol3,
  sws1,
  sws2,
  sws3,
  fluidra1,
  fluidra2,
  fluidra3,
  fluidra4,
  fluidra5,
  lalanne1,
  lalanne10,
  lalanne2,
  lalanne3,
  lalanne4,
  lalanne5,
  lalanne6,
  lalanne7,
  lalanne8,
  lalanne9,
  hp831,
  hp832,
  hp833,
  hp834,
  hp835,
  hp836,
  hp837,
  gran1,
  gran2,
  gran3,
  terrassa1,
  terrassa2,
  terrassa3,
  terrassa4,
  hp8111,
  hp8112,
  hp8113,
  hp8131,
  hp8132,
  hp8133,
  hp8134,
  hp8135,
  artrux1,
  artrux2,
  artrux3,
  artrux4,
  artrux5,
  hu0051,
  hu0052,
  hu0053,
  hu0054,
  hu0055,
  hu0056,
  hu081,
  hu082,
  hu083,
  hu084,
  hu085,
  gcz1,
  gcz2,
  gcz3,
  gcz4,
  gcz5,
  blh1,
  blh2,
  blh3,
  blh4,
  blh5,
  blh6,
  blh7,
  im561,
  im562,
  im563,
  hu831,
  hu832,
  vts1,
  vts2,
  vts3,
  vts4,
  vts5,
  vts6,
  vts7,
  ccev1,
  ccev2,
  ccev3,
  iscola1,
  iscola2,
  ondara1,
  ondara2,
  hp1,
  water1,
  water2,
  water3,
  water4,
  water5,
  water6,
  iglesia1,
  iglesia2,
  iglesia3,
  iglesia4,
  iglesia5,
  iglesia6,
  wbf1,
  wbf2,
  wbf3,
  wbf4,
  wbf5,
  nova1,
  nova2,
  corus1,
  corus2,
  corus3,
  corus4,
  corus5,
  corus6,
  can1,
  can2,
  can3,
  can4,
  hu6491,
  hu6492,
  hu6493,
  hu6494,
  hu6495,
  cugat1,
  cugat2,
  cugat3,
  cugat4,
  cugat5,
  cugat6,
  cugat7,
  boardriders1,
  boardriders2,
  boardriders3,
  boardriders4,
  boardriders5,
  cartama1,
  cartama2,
  cartama3,
  cartama4,
  cartama5,
  cartama6,
  mina1,
  mina2,
  mina3,
  mina4,
  sm1,
  sm2,
  sm3,
  sm4,
  campus1,
  campus10,
  campus11,
  campus2,
  campus3,
  campus4,
  campus5,
  campus6,
  campus7,
  campus8,
  campus9,
  oasis1,
  oasis2,
  oasis3,
  oasis4,
  olot1,
  olot2,
  olot3,
  sws4,
} from "../assets";

const proyectosCA = [
  {
    ref: "DA0005",
    short: "VLLV",
    title: "HU005",
    categoria: "inmobiliari",
    location: "Vallvidrera - Barcelona",
    superficie: 295,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 6,
    año: 2000,
    images: [hu0051, hu0052, hu0053, hu0054, hu0055, hu0056],
    description:
      "Habitatge unifamiliar de nova planta a l’entorn urbà de Barcelona. Optimització dels recursos de l’emplaçament mitjançant la creació de patis interiors i exteriors que milloren la privacitat i la il·luminació natural de l’habitatge.",
  },
  {
    ref: "DA0008",
    short: "",
    title: "HU008",
    categoria: "inmobiliari",
    location: "Matadepera - Barcelona",
    superficie: 235,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 7,
    año: 2000,
    images: [hu081, hu082, hu083, hu084, hu085],
    description:
      "Habitatge unifamiliar situat al límit del sòl urbà i enfront un espai d’alt valor ecològic. El projecte compacta l’edificabilitat alliberant la major part de la parcel·la i desdibuixa el volum reduint la lectura de la seva altura i presencia. L’habitatge es lluminós, en relació directa amb l’espai natural que l’envolta.",
  },
  {
    ref: "DA0056",
    short: "IM0056",
    title: "IM0056",
    categoria: "inmobiliari",
    location: "Sant Feliu de Llobregat - Barcelona",
    superficie: 855,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 4,
    año: 2005,
    images: [im561, im562, im563],
    description:
      "Edifici logístic i d’oficines. Construcció modular i prefabricada per millorar la seva posada en obra. Les oficines de la façana principal s’integren en el material de tancament, quedant protegides per un brise-solei metàl·lic que permet una escala industrial en els materials i solucions domèstiques per a l’usuari.",
  },
  {
    ref: "DA0083",
    short: "IH0083",
    title: "IH0083",
    categoria: "inmobiliari",
    location: "Barcelona",
    superficie: 185,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [hu831, hu832],
    description: "",
  },
  {
    ref: "DA0309",
    short: "ISCOLA",
    title: "Edificio Iscola",
    categoria: "inmobiliari",
    location: "Benicarló (Castelló)",
    superficie: 19850,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [iscola1, iscola2],
    description:
      "Edifici plurifamiliar de 112 habitatges, zones comuns, locals comercials i aparcaments.",
  },
  {
    ref: "DA0312",
    short: "ONDARA",
    title: "Edificio Ondara",
    categoria: "inmobiliari",
    location: "Tàrrega (Lleida)",
    superficie: 6182,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 8,
    año: null,
    images: [ondara1, ondara2],
    description:
      "Edifici plurifamiliar de 41 habitatges, zones comuns, local comercial y aparcaments",
  },
  {
    ref: "DA0322",
    short: "HP0322",
    title: "HP0322",
    categoria: "inmobiliari",
    location: "Barcelona",
    superficie: 1188,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [hp1],
    description:
      "Edifici plurifamiliar entre mitjaneres de 12 habitatges a Barcelona.",
  },
  {
    ref: "DA369",
    short: "C. NOVA",
    title: "Edifici Ciutat Nova",
    categoria: "inmobiliari",
    location: "Benicarló (Castelló)",
    superficie: 3945,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [nova1, nova2],
    description:
      "Edifici plurifamiliar de 47 habitatges, zones comuns, local comercial y aparcaments.",
  },
  {
    ref: "DA0649",
    short: "HU0649",
    title: "HABITATGE VALLDOREIX",
    categoria: "inmobiliari",
    location: "",
    superficie: null,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [hu6491, hu6492, hu6493, hu6494, hu6495],
    description:
      "Habitatge unifamiliar a Valldoreix (Barcelona). El projecte maximitza els espais relacionals entre tres nuclis compactes de major intimitat. El menjador, la sala d’estar i l’estudi professional s’obren a la vegetació circumdant amb visuals diagonals, incorporant l’espai a l’interior. Les altures dels espais, la seva compacitat o transparència proposen diferents formes de viure’ls, però només els hi dóna sentit l’ús que en fa d’ells la família que els habita. Compartir un esmorzar amb ells dóna sentit final a tot el projecte i converteix la matèria en sentiments.",
  },
  {
    ref: "DA0803",
    short: "HP0803",
    title: "HP0803",
    categoria: "inmobiliari",
    location: "Barcelona",
    superficie: 85,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Berkshire Hathaway"],
    fotografia: "",
    orden: 5,
    año: 2022,
    images: [hp831, hp832, hp833, hp834, hp835, hp836, hp837],
    description:
      "Divisió i segregació d’un immoble en dos nous habitatges. Estudi de possibilitats de projecte, renovació energètica i selecció de la gestió de projecte i obres.",
  },
  {
    ref: "DA0811",
    short: "HP0811",
    title: "HP0811",
    categoria: "inmobiliari",
    location: "Sant Cugat del Vallès ( Barcelona)",
    superficie: 1399,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 4,
    año: null,
    images: [hp8111, hp8112, hp8113],
    description:
      "Edifici plurifamiliar de 9 habitatges, zones comuns, local comercial y aparcaments.",
  },
  {
    ref: "DA0813",
    short: "HP0813",
    title: "HP0813",
    categoria: "inmobiliari",
    location: "Barcelona",
    superficie: 225,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Berkshire Hathaway"],
    fotografia: "",
    orden: 5,
    año: 2023,
    images: [hp8131, hp8132, hp8133, hp8135, hp8134],
    description:
      "Reforma d’habitatge a Barcelona. Estudi de possibilitats de projecte, renovació energètica i selecció de la gestió de projecte i obres.",
  },

  {
    ref: "DA0010",
    short: "GCZ",
    title: "Gran Cafe Zaragoza",
    categoria: "patrimoni",
    location: "Zaragoza",
    superficie: 180,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Carmen Sisquella"],
    fotografia: "",
    orden: 4,
    año: 2000,
    images: [gcz1, gcz2, gcz3, gcz4, gcz5],
    description:
      "Reforma de l'emblemàtic establiment del carrer Alfonso I de Saragossa obra de l'arquitecte local Luís Aladrén el 1885, amb un estil eclèctic i historicista propi de finals del s. XIX. El comerç original, amb una gran façana cantonera es va destinar a una afamada joieria per a la nova burgesia de la ciutat. Els expositors envidrats i els sostres enteixinats de l'interior transmetien el luxe que ostentava el comerç de plata i joies. El projecte va transformar l'ús comercial al de la nova propietat 'Gran Café Saragossa' que més tard es mantindria com 'Cafè 1885'. Les sales interiors es netegen de cortinatges, donant un major protagonisme a les columnes de fosa i els treballats sostres enteixinats. Local declarat Bé Catalogat del Patrimoni Cultural Aragonès pel Govern d'Aragó des del 2002.",
  },
  {
    ref: "DA0569",
    short: "STA MARIA",
    title: "Santa Maria 33",
    categoria: "patrimoni",
    location: "Sant Cugat del Vallès ( Barcelona)",
    superficie: 165,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Carmen Sisquella"],
    fotografia: "",
    orden: 3,
    año: 2017,
    images: [sm1, sm2, sm3, sm4],
    description:
      "Actuació en una petita edificació de valor històric al nucli antic de Sant Cugat del Vallès. L'habitatge tradicional abandonat s'actualitza al nou ús en el principal carrer comercial del municipi, mantenint l'ús d'habitatge a la planta primera. Es recuperen i posen en valor la façana principal, la tradicional estructura de 'volta' i els rastells de coberta. També es tracten i eliminen les humitats de capil·laritat i l'atac a l'estructura de coberta per part de termites i humitats. Edifici declarat BCIL (Bé Cultural d'Interès Local).",
  },
  {
    ref: "DA0573",
    short: "UVIC-CAMPUS",
    title: "Uvic Campus Casa Convalescencia",
    categoria: "patrimoni",
    location: "Vic ( Barcelona)",
    superficie: 4050,
    promotor: "Universitat de Vic",
    equipo: ["D'Aura Arquitectura", "Vives-Bassa-Ayala SCP"],
    fotografia: "",
    orden: 2,
    año: null,
    images: [
      campus1,
      campus10,
      campus11,
      campus2,
      campus3,
      campus4,
      campus5,
      campus6,
      campus7,
      campus8,
      campus9,
    ],
    description:
      "Restauració de l’antiga Casa de Convalescència de l’Hospital de la Santa Creu de Vic, obra de l’arquitecte Josep Morató i Codina, construït a cavall entre el barroc (finals s.XVIII) i el neoclassicisme (principis s.XIX). Es tracta d’una actuació de 4000 m2 d’edifici, situat al límit de l’antiga muralla medieval de Vic. L’objectiu de l’actuació es reutilitzar l’edifici com a seu del Rectorat de la universitat de Vic i un centre d’expenedoria i co-working, creació. Durant el procés han estat involucrats la Universitat de Vic, l’ajuntament de Vic i el patronat de l’Hospital de la Santa Creu, com a propietari de l’edifici, durant els casi 14 anys que durat la intervenció completa. L’edifici es trobava en mal estat de conservació, però presentava una riquesa constructiva i uns espais arquitectònics de molta qualitat, incloent un claustre neoclàssic, 24 voltes barroques i pintures de gran qualitat. S’ha recuperat el claustre i totes les circulacions al voltant d’aquest. L’esperit restaurador ens ha portat a recuperar les fusteries existents ben conservades, millorant el comportament tèrmic. S’han conservat, també, reparant o reforçant la major par de l’estructura de fusta i les voltes existents.",
  },
  {
    ref: "DA0621",
    short: "PARANINF",
    title: "Antigua Esglesia de la Santa Creu de Vic y Sala Gótica-Paraninf",
    categoria: "patrimoni",
    location: "Vic ( Barcelona)",
    superficie: 4050,
    promotor: "Universitat de Vic",
    equipo: ["D'Aura Arquitectura", "Vives-Bassa-Ayala SCP"],
    fotografia: "",
    orden: 1,
    año: null,
    images: [iglesia1, iglesia2, iglesia3, iglesia4, iglesia5, iglesia6],
    description:
      "L’església de la Santa Creu, obra de Josep Morató i Sellés, es va construir entre el 1748 i el 1753. És una única nau d’imponent volumetria arquitectònica, on destaca especialment el cambril, esplèndidament ornamentat. La decoració pictòrica interior ha estat restaurada en diferents etapes històriques, amb major o menor encert, quedant finalment un estil recarregat. Tot el conjunt arquitectònic és barroc i de transició neoclàssica. Es restaura i s’incorpora a l’ús del paranimf una sala adossada a l’església d’origen gòtic amb grans arcs ogivals pertanyents en origen a l’Hospital de la Santa Creu. Aquesta restauració integral ha permès recuperar i posar en valor l’obra de tota una saga d’artistes i mestres d’obra importantíssims d’un període històric a Catalunya, entre els segles XVII – XVIII : La nissaga vigatana dels Morató. Edifici declarat BCIL (Bé Cultural d’interès local).",
  },
  {
    ref: "DA0722",
    short: "FJB",
    title: "Casa Francesc Lalanne",
    categoria: "patrimoni",
    location: "Barcelona",
    superficie: null,
    promotor: "Fundació Jaume Bofill",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "",
    orden: 3,
    año: null,
    images: [
      lalanne1,
      lalanne2,
      lalanne3,
      lalanne4,
      lalanne5,
      lalanne6,
      lalanne7,
      lalanne8,
      lalanne9,
      lalanne10,
    ],
    description:
      "Conjunt d’actuacions a la casa Francesc Lalanne, també conegudes com Casa Armentera i Parellada, de l’Eixample de Barcelona. S’intervé en aquest edifici de 1908-1910, recuperant elements històrics ocults per intervencions prèvies, realitzant un detallat anàlisis estructural, i adaptant els espais a noves necessitats de la Fundació propietària de l’edifici. La valorització de les voltes paredades i els paviments de Nolla posen en context l’edificació projectada per l’arquitecte del s. XIX – XX Arnau Calvet. 1r Premi Concurs de projectes. Edifici declarat BCIL (Bé Cultural d’interès local).",
  },
  {
    ref: "DA0804",
    short: "ARTRUTX",
    title: "Talaia D'Artrutx",
    categoria: "patrimoni",
    location: "Ciutadella de Menorca ( Balears)",
    superficie: 115,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 5,
    año: null,
    images: [artrux1, artrux2, artrux3, artrux4, artrux5],
    description:
      "Les Talaies són interessants torres d'observació ubicades estratègicament al voltant de la costa menorquina. La Talaia d'Artruts està ubicada a la costa sud-oest de Menorca i datada entre finals del segle XVI i principis del s. XVII. És un Bé d'Interès Cultural (BIC) identificat en el Catàleg de protecció del Patrimoni Històric de Ciutadella. El projecte consolida l'edificació amb materials locals i tradicionals i recupera elements eliminats. L'actuació permetrà evitar el deteriorament progressiu i la futura visita de l'edifici.",
  },
  {
    ref: "DA0015",
    short: "LA FRASCA",
    title: "Bodega R. Lopez de Heredia",
    categoria: "arquitectura",
    location: "Haro (La Rioja)",
    superficie: 680,
    promotor: "R. López de Heredia",
    equipo: ["D'Aura Aquitectura", "Zaha Hadid Architects", "IOA"],
    fotografia: "",
    orden: 2,
    año: 2006,
    images: [blh1, blh2, blh3, blh4, blh5, blh6, blh7],
    description:
      "Sales de tast, pati de recepcions i edifici d'atenció al visitant a les Bodegues R. López de Heredia.Com a arquitectes locals, en col·laboració amb Zaha Hadid Arch., hem experimentat amb el disseny d'espais arquitectònics, solucions estructurals innovadores i nous materials, que serveixen com a referència per a la renovació d'una bodega familiar centenària. El resultat ha afegit nous valors en relació a la cultura tradicional de 'Viña Tondonia'. L'edifici de recepció, conté al seu interior el pavelló de mostres que Viña Tondonia va exposar a la fira de 1910. El nou contenidor modular va ser concebut inicialment per participar en noves fires, i finalment, s'erigeix com a punt d'accés per als visitants de la bodega. Tant 'La Frasca', com els espais exteriors, el nou accés a la bodega o les sales de tast incorporen solucions tecnològicament innovadores per proporcionar al visitant un nou apropament a la bodega, a l'experiència del vi i dels seus paisatges.",
  },
  {
    ref: "DA0118",
    short: "VTDN",
    title: "Viña Tondonia Stand",
    categoria: "arquitectura",
    location: "Barcelona",
    superficie: 680,
    promotor: "R. López de Heredia",
    equipo: ["D'Aura Aquitectura", "IOA"],
    fotografia: "Marcela Grassi",
    orden: 4,
    año: null,
    images: [vts1, vts2, vts3, vts4, vts5, vts6, vts7],
    description:
      "Arquitectura efímera per a la imatge de la marca de la Bodega en esdeveniments internacionals. El projecte de reduïdes dimensions inclou l’exhibició de la marca, dels seus productes i l’espai per a l’atenció dels visitats i degustació de productes. La imatge gràfica de la bodega centenària i el característic color or vell del seu Gran Reserva blanc adquireixen tot el protagonisme en un estand íntim i singular. Les formes orgàniques acompanyen al visitant cap a les vinyes de la Rioja alta i les galeries subterrànies junt al riu Ebre. ",
  },
  {
    ref: "DA0138",
    short: "VIENESOS",
    title: "Centre Cívic els Vienesos",
    categoria: "arquitectura",
    location: "El Masnou (Barcelona)",
    superficie: null,
    promotor: "Ajuntament El Masnou",
    equipo: ["D'Aura Aquitectura", "IOA"],
    fotografia: "",
    orden: 6,
    año: null,
    images: [ccev1, ccev2, ccev3],
    description:
      "Ampliació del Centre Cívic  “Els Vienesos” amb noves sales multiús, aularis i una nova planta. El projecte unifica els espais existents i l’ampliació oferint una nova façana urbana i significativa a l’espai coplanar contigu.",
  },
  {
    ref: "DA0470",
    short: "CA LA MINA",
    title: "Centre Cívic CA La Mina",
    categoria: "arquitectura",
    location: "Montcada i Rexac (Barcelona)",
    superficie: 1200,
    promotor: "Ajuntament Montcada i Rexac",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 7,
    año: null,
    images: [mina1, mina2, mina3, mina4],
    description:
      "Ampliació del Centre cívic del “Parc de les Aigües”. L’objectiu principal d’aquest projecte era trobar una forma creativa i eficient per ampliar el centre cívic existent. Aquest centre està construït sobre la històrica mina d’aigua de Montcada i Reixac, que alimenta el “Rec Comtal” a través d’una via d’aigua romana paral·lela al riu Besos. Per tant, el projecte havia de créixer verticalment i havia de resoldre’s amb la creació d’una nova planta sobre el sostre existent, que va obrir visualment l'edifici fins a l'entorn natural que l'envolta. Es proposa també una nova entrada des de la part posterior de l'edifici, el carrer que connecta Montcada centre amb el barri de Can Sant Joan. L'ampliació va ser construïda amb components lleugers prefabricats que connecten l'edifici existent amb la nova construcció.",
  },
  {
    ref: "DA0523",
    short: "BOARDRIDERS",
    title: "Boardriders Barceloneta",
    categoria: "architecture",
    location: "Barcelona",
    superficie: 290,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "",
    orden: null,
    año: null,
    images: [
      boardriders1,
      boardriders2,
      boardriders3,
      boardriders4,
      boardriders5,
    ],
    description:
      "Reconversió d'un edifici industrial al front marítim de Barcelona.La transformació d'un antic espai industrial i la seva obertura al nou front marítim va propiciar l'aparició d'espais disfuncionals i sense encaix urbà. La intervenció en aquests espais ha de permetre l'arribada de nous usos, la seva actualització i una nova integració a l'espai urbà transformat. Amb aquestes premisses, el projecte manté el caràcter dels espais existents, recuperant estructures i materials però incorporant les activitats urbanes d'oci i comerç que han colonitzat la façana marítima.",
  },
  {
    ref: "DA0628",
    short: "CORUS",
    title: "Corus Laboratories",
    categoria: "arquitectura",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: 685,
    promotor: "Corus Dental Institute",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "Marcela Grassi",
    orden: 2,
    año: null,
    images: [corus1, corus2, corus3, corus4, corus5, corus6],
    description:
      "Headquarters i laboratoris de multinacional sanitària a Espanya. Els processos productius dels nous laboratoris son els motiu principal d’aquest projecte. S’utilitzen diferents graus de transparència en la sectorització dels espais per mostrar i relacionar les activitats. La circulació  dels materials i de la informació defineix les distribucions i els espais. El treball amb els diferents departaments de l’empresa fa que l’edifici esdevingui també imatge corporativa i el posicioni l’empresa en el sector.",
  },
  {
    ref: "DA0681",
    short: "BIB SCG",
    title: "Biblioteca Central Sant Cugat",
    categoria: "arquitectura",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: null,
    promotor: "Ajuntament de Sant Cugat",
    equipo: ["D'Aura Arquitectura", "Arturo Frediani"],
    fotografia: "",
    orden: 2,
    año: 2017,
    images: [cugat1, cugat2, cugat3, cugat4, cugat5, cugat6, cugat7],
    description:
      "Nou edifici de la Biblioteca Gabriel Ferrater al parc Ramon Barnils de Sant Cugat del Vallès. 3r premi concurs de projectes. El projecte emergeix del paisatge com una antiga fortificació atemporal i sense nom. Imaginem la biblioteca com un refugi envolupant de llibres, un edifici ple de racons lluminosos, solitaris o col·lectius, on trobar tant la calma de la lectura com l’estímul de la trobada i intercanvi d’idees. Els espais interiors no son rectangulars, sinó polígons de 5 o 6 costats. D’aquesta forma amb les prestatgeries podem crear espais que abracin el lector sense restringir els seus moviments, i al mateix temps augmentem fins un 50% la capacitat d’emmagatzematge. El parc forma part de l’edifici i l’edifici del parc, relacionant els espais interiors i exteriors. Les cobertes es confonen visualment amb el parc i pel seu esglaonament deixen veure la vista llunyana del Monestir de Sant Cugat, tan present al municipi, i amb qui la biblioteca guardarà una ressonància formal i conceptual. Contemporani és compatible amb Històric.",
  },
  {
    ref: "DA0729",
    short: "OASIS",
    title: "Hotel Oasis",
    categoria: "arquitectura",
    location: "Marbella (Málaga)",
    superficie: 650,
    promotor: "Selenta Group",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: 2020,
    images: [oasis1, oasis2, oasis3, oasis4],
    description:
      "Zona d’aigües i lounge bar per a l’Hotel Oasis (Marbella). Els materials naturals i la vegetació caracteritzen el projecte per crear un espai relaxant i diferenciat de la resta de les activitats de l’hotel. La piscina és un espai social junt amb el lounge bar que s’obre o es tanca a aquest, segons els horaris i les activitats programades. L’aigua és un element més del projecte paisatgístic del jardí, incorporant la naturalesa propera i la més llunyana de la Serra Blanca.",
  },
  {
    ref: "DA0603",
    short: "WBF",
    title: "World Basket Festival",
    categoria: "sport",
    location: "Barcelona",
    superficie: 2500,
    promotor: "Nike",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 3,
    año: null,
    images: [wbf1, wbf2, wbf3, wbf4, wbf5],
    description:
      "Instal·lació esportiva amb motiu del Mundial de Bàsquet de Barcelona. Més enllà de la competició professional d’un mundial de Bàsquet, l’esport urbà és una activitat d’oci i socialització. Aquesta instal·lació combina espais d’activitat física i competició, amb espectacles esportius, musicals i zones d’oci. Tot i la seva breu durada temporal, el seu impacte urbà ha atret més de 30.000 visitants. Tots els elements de la instal·lació són de construcció lleugera i reutilitzables per a nous esdeveniments.",
  },
  {
    ref: "DA0691",
    short: "WP'18",
    title: "Waterpolo BCN'18 Campeonato de Europa",
    categoria: "sport",
    location: "Barcelona",
    superficie: 2480,
    promotor: "Federeació Catalana de Natació",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [water1, water2, water3, water4, water5, water6],
    description:
      "Reforma de les piscines Bernat Picornell per allotjar el 33º Campionat d’Europa de Waterpolo Barcelona 2018. Es projecte un nou espai de piscina descoberta, configurant graderies per a 3.700 espectadors, una gran pèrgola, escenari i pantalles de projecció al voltant de la làmina d’aigua per crear un espai únic i memorable per a aquest esdeveniment esportiu. Es reformes i redistribueixen els vestuaris i espais annexes per allotjar els equips esportius, els tècnics de gestió de competició i televisions. Els espais exteriors s’adapten per acollir el Village,  espais per al públic i la imatge exterior de l’esdeveniment. ",
  },
  {
    ref: "DA0695",
    short: "C.N. OLOT",
    title: "C.N. OLOT",
    categoria: "sport",
    location: "Olot (Girona)",
    superficie: 3200,
    promotor: "C.N. Olot",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [olot1, olot2, olot3],
    description:
      "Projecte de rehabilitació i ampliació de les instal·lacions esportives del Club Natació Olot. La intervenció sobre l’equipament existent preserva els espais funcionals i crea un nou tancament i estructura de coberta per a la piscina principal. Els espais exteriors es relacionen amb l’activitat interior, permetent un us més permeable a l’estiu.",
  },
  {
    ref: "DA0714",
    short: "MIRASOL",
    title: "Piscina Municipal Mirasol",
    categoria: "sport",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: null,
    promotor: "Ajuntament Sant Cugat",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [mirasol1, mirasol2, mirasol3],
    description:
      "L’edifici es situa a la parcel·la assignada, buscant un assentament fàcil i natural sobre el terreny i es separa lleugerament per connectar amb el seu voltant. Es pretén crear un volum atractiu i compacte que s’integri amb l’edificació i el seu entorn proper. La proposta diferencia els espais de pràctica esportiva, sala de piscina i demés estàncies, atorgant a aquells un caràcter preferent i representatiu. La resta d’espais s’organitzen ordenats en franges o paquets longitudinals de programa, coherents amb els esquemes de circulació propis de les instal·lacions esportives. 3r premi concurs de projectes. ",
  },
  {
    ref: "DA0720",
    short: "FWS-21",
    title: "Fina Artistic Swimming World Series 2021",
    categoria: "sport",
    location: "Barcelona",
    superficie: 1500,
    promotor: "Federació Catalana Natació",
    equipo: [],
    fotografia: "",
    orden: 8,
    año: null,
    images: [sws1, sws2, sws3, sws4],
    description:
      "Arquitectura efímera per a la celebració a Barcelona de les World Series 2021 de natació artística i el torneig de classificació Olímpica per a Tokio 2021. Transformació de l’equipament esportiu per adequar-lo a les necessitats normatives de la competició i a les arquitectòniques dels espectadors i les retransmissions de l’espectacle. Estudi dels ambients, il·luminació i diferents usos de la làmina d’aigua i escenaris adjacents per crear una imatge global reconeguda a l’espectador.",
  },
  {
    ref: "DA0733",
    short: "50'S",
    title: "Fluidra 50'S Anniversary",
    categoria: "sport",
    location: "Barcelona",
    superficie: 1500,
    promotor: "Fluidra",
    equipo: ["D'Aura Arquitectura", "Franc Aleu", "Fluidra Engineering"],
    fotografia: "",
    orden: 6,
    año: null,
    images: [fluidra1, fluidra2, fluidra3, fluidra4, fluidra5],
    description:
      "Projecte d’investigació amb un meravellós equip per a la creació d’un espectacle audiovisual dintre de l’aigua. L’espectacle, amb una potent narrativa audiovisual es desenvolupa sobre i sota la superfície de l’aigua, utilitzant aquest element amb la seva màxima expressivitat gràcies a l’ús de fonts, plataformes i il·luminació que potencien la coreografia de nedadores i ballarines. Creació de nous elements tècnics com la plataforma central usada com escenari i projector d’aigua, llum i so.",
  },
  {
    ref: "DA0745",
    short: "CNT",
    title: "Club Natació Terrassa",
    categoria: "sport",
    location: "Terrassa (Barcelona)",
    superficie: 3220,
    promotor: "Club Natació Terrassa",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [terrassa1, terrassa2, terrassa3, terrassa4],
    description:
      "Piscina d’entrenament i competició al Club Natació Terrassa. El projecte dota la instal·lació d’una nova piscina per a activitats esportives, convertible en dos piscines de competició de waterpolo mitjançant un pont mòbil. La nova construcció s’insereix entre les existents, proposant una solució compacta i eficient. El volum rememora el passat industrial de la zona però amb la lleugeresa dels actuals sistemes constructius prefabricats. La llum natural i el control de les vistes defineixen la proporció dels forats i espais, i la relació amb la resta de volums existents.",
  },
  {
    ref: "DA0758",
    short: "CNG",
    title: "Club Natació Granollers",
    categoria: "sport",
    location: "Granollers (Barcelona)",
    superficie: 3590,
    promotor: "Ajuntament Granollers",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [gran1, gran2, gran3],
    description:
      "Projecte de les noves piscines municipals al Club Natació Granollers. 1er premi concurs. La substitució de les piscines originals de la instal·lació, amb més de 50 anys, permet utilitzar nous sistemes constructius prefabricats i optar per solucions d’alta eficiència energètica que redueixin el consum i millorin el confort dels usuaris. El nou volum dóna continuïtat al llenguatge de materials de la instal·lació, amb noves aplicacions tecnològiques. La llum natural i l’eficiència energètica condueixen cap a una bona part de les solucions.",
  },
  {
    ref: "DA0759",
    short: "CARTAMA",
    title: "COMPLEX AQÜÀTIC DE LA CIUTAT ESPORTIVA DE CÀRTAMA",
    categoria: "sport",
    location: "Cártama (Málaga)",
    superficie: null,
    promotor: "Ayuntamiento de Cártama",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [cartama1, cartama2, cartama3, cartama4, cartama5, cartama6],
    description:
      "Equipament esportiu amb piscina coberta i espais polivalents annexes. 1r premi Concurs de projectes. El projecte proposa una instal·lació que defensa l’escala urbana del complex. L’espai esportiu com a infraestructura que en aquest cas articula la connexió entre els dos nuclis urbans del municipi. A una escala intermèdia, l’edifici de la zona d’aigües intervé en l’organització de tota la ciutat esportiva definint els accessos i la centralitat dels espais. En una escala menor, el projecte proposa un edifici compacte i d’alta eficiència energètica; orientat a l’usuari i a una gestió sostenible.",
  },
  {
    ref: "DA0802",
    short: "CAN RABASSA",
    title: "Piscina Municipal Can Rabassa",
    categoria: "sport",
    location: "Vilanova del Vallès (Barcelona)",
    superficie: 1200,
    promotor: "Ajuntament Vilanova del Vallès",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [can1, can2, can3, can4],
    description:
      "Equipament municipal esportiu i d’oci. 1r premi Concurs. El nou complex d’oci i esport s’ubica junt a la Masia Can Rabassa, millorant les seves prestacions i posant en valor la seva història i els seus espais naturals circumdants. Redacció d’un Pla director del complex preveient futurs creixements i ampliació d’activitats, així com la connexió amb el Parc Natural de la Serralada Litoral. L’equipament consta d’una piscina mixta (oci/ensenyament), zones naturals i d’oci i un edifici lleuger amb els serveis.",
  },
];

const colorsCA = {
  tots: "#DF6537",
  arquitectura: "#203457",
  sport: "#7F9052",
  patrimoni: "#7F403B",
  inmobiliari: "#CBA971",
};

export { proyectosCA, colorsCA };
