import {
  mirasol1,
  mirasol2,
  mirasol3,
  sws1,
  sws2,
  sws3,
  fluidra1,
  fluidra2,
  fluidra3,
  fluidra4,
  fluidra5,
  lalanne1,
  lalanne10,
  lalanne2,
  lalanne3,
  lalanne4,
  lalanne5,
  lalanne6,
  lalanne7,
  lalanne8,
  lalanne9,
  hp831,
  hp832,
  hp833,
  hp834,
  hp835,
  hp836,
  hp837,
  gran1,
  gran2,
  gran3,
  terrassa1,
  terrassa2,
  terrassa3,
  terrassa4,
  hp8111,
  hp8112,
  hp8113,
  hp8131,
  hp8132,
  hp8133,
  hp8134,
  hp8135,
  artrux1,
  artrux2,
  artrux3,
  artrux4,
  artrux5,
  hu0051,
  hu0052,
  hu0053,
  hu0054,
  hu0055,
  hu0056,
  hu081,
  hu082,
  hu083,
  hu084,
  hu085,
  gcz1,
  gcz2,
  gcz3,
  gcz4,
  gcz5,
  blh1,
  blh2,
  blh3,
  blh4,
  blh5,
  blh6,
  blh7,
  im561,
  im562,
  im563,
  hu831,
  hu832,
  vts1,
  vts2,
  vts3,
  vts4,
  vts5,
  vts6,
  vts7,
  ccev1,
  ccev2,
  ccev3,
  iscola1,
  iscola2,
  ondara1,
  ondara2,
  hp1,
  water1,
  water2,
  water3,
  water4,
  water5,
  water6,
  iglesia1,
  iglesia2,
  iglesia3,
  iglesia4,
  iglesia5,
  iglesia6,
  wbf1,
  wbf2,
  wbf3,
  wbf4,
  wbf5,
  nova1,
  nova2,
  corus1,
  corus2,
  corus3,
  corus4,
  corus5,
  corus6,
  can1,
  can2,
  can3,
  can4,
  hu6491,
  hu6492,
  hu6493,
  hu6494,
  hu6495,
  cugat1,
  cugat2,
  cugat3,
  cugat4,
  cugat5,
  cugat6,
  cugat7,
  boardriders1,
  boardriders2,
  boardriders3,
  boardriders4,
  boardriders5,
  cartama1,
  cartama2,
  cartama3,
  cartama4,
  cartama5,
  cartama6,
  mina1,
  mina2,
  mina3,
  mina4,
  sm1,
  sm2,
  sm3,
  sm4,
  campus1,
  campus10,
  campus11,
  campus2,
  campus3,
  campus4,
  campus5,
  campus6,
  campus7,
  campus8,
  campus9,
  oasis1,
  oasis2,
  oasis3,
  oasis4,
  olot1,
  olot2,
  olot3,
  sws4,
} from "../assets";

const proyectosEN = [
  {
    ref: "DA0005",
    short: "VLLV",
    title: "HU005",
    categoria: "real estate",
    location: "Vallvidrera - Barcelona",
    superficie: 295,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 6,
    año: 2000,
    images: [hu0051, hu0052, hu0053, hu0054, hu0055, hu0056],
    description:
      "New single-family house in the urban environment of Barcelona. Optimization of the site's resources by creating interior and exterior patios that improve the privacy and natural lighting of the home.",
  },
  {
    ref: "DA0008",
    short: "",
    title: "HU008",
    categoria: "real estate",
    location: "Matadepera - Barcelona",
    superficie: 235,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 7,
    año: 2000,
    images: [hu081, hu082, hu083, hu084, hu085],
    description:
      "Single-family home on the edge of urban land and in front of a space of high ecological value. The project compacts the building area, freeing up most of the plot and blurs the volume, reducing the reading of its height and presence. The house is bright, in direct relation with the natural space that surrounds it.",
  },
  {
    ref: "DA0056",
    short: "IM0056",
    title: "IM0056",
    categoria: "real estate",
    location: "Sant Feliu de Llobregat - Barcelona",
    superficie: 855,
    promotor: "",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 4,
    año: 2005,
    images: [im561, im562, im563],
    description:
      "Logistics and office building. Modular and prefabricated construction improving its implementation. The offices on the main façade are integrated into the enclosure material, being protected by a metallic brisesoleil that allows an industrial scale in the materials and domestic solutions for the user.",
  },
  {
    ref: "DA0083",
    short: "IH0083",
    title: "IH0083",
    categoria: "real estate",
    location: "Barcelona",
    superficie: 185,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [hu831, hu832],
    description: "",
  },
  {
    ref: "DA0309",
    short: "ISCOLA",
    title: "Edificio Iscola",
    categoria: "real estate",
    location: "Benicarló (Castelló)",
    superficie: 19850,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [iscola1, iscola2],
    description:
      "Multi-family building with 112 homes, common areas, commercial premises and car parks.",
  },
  {
    ref: "DA0312",
    short: "ONDARA",
    title: "Edificio Ondara",
    categoria: "real estate",
    location: "Tàrrega (Lleida)",
    superficie: 6182,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 8,
    año: null,
    images: [ondara1, ondara2],
    description:
      "Multi-family building with 41 homes, common areas, commercial premises and parking lots.",
  },
  {
    ref: "DA0322",
    short: "HP0322",
    title: "HP0322",
    categoria: "real estate",
    location: "Barcelona",
    superficie: 1188,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [hp1],
    description:
      "Multi-family building between median of 12 homes in Barcelona.",
  },
  {
    ref: "DA369",
    short: "C. NOVA",
    title: "Edifici Ciutat Nova",
    categoria: "real estate",
    location: "Benicarló (Castelló)",
    superficie: 3945,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [nova1, nova2],
    description:
      "Multi-family building with 47 homes, common areas, commercial premises and parking lots.",
  },
  {
    ref: "DA0649",
    short: "HU0649",
    title: "HU0649",
    categoria: "real estate",
    location: "",
    superficie: null,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [hu6491, hu6492, hu6493, hu6494, hu6495],
    description:
      "Detached house in Valldoreix (Barcelona). The project maximizes the relational spaces between three compact nuclei of greater privacy. The dining room, living room and professional study open to the surrounding vegetation with diagonal visuals, incorporating the space into the interior. The heights of the spaces, their compactness or their transparency propose different ways of living them, but only the use that the family that inhabits them makes of them gives them meaning. Sharing a breakfast with them gives final meaning to the whole project and turns matter into feelings.",
  },
  {
    ref: "DA0803",
    short: "HP0803",
    title: "HP0803",
    categoria: "real estate",
    location: "Barcelona",
    superficie: 85,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Berkshire Hathaway"],
    fotografia: "",
    orden: 5,
    año: 2022,
    images: [hp831, hp832, hp833, hp834, hp835, hp836, hp837],
    description:
      "Division and segregation of a property into two new homes. Study of project alternatives, energy renovation and selection of project and works management.",
  },
  {
    ref: "DA0811",
    short: "HP0811",
    title: "HP0811",
    categoria: "real estate",
    location: "Sant Cugat del Vallès ( Barcelona)",
    superficie: 1399,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 4,
    año: null,
    images: [hp8111, hp8112, hp8113],
    description:
      "Multi-family building with 9 homes, common areas, commercial premises and parking lots.",
  },
  {
    ref: "DA0813",
    short: "HP0813",
    title: "HP0813",
    categoria: "real estate",
    location: "Barcelona",
    superficie: 225,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Berkshire Hathaway"],
    fotografia: "",
    orden: 5,
    año: 2023,
    images: [hp8131, hp8132, hp8133, hp8135, hp8134],
    description:
      "Housing reform in Barcelona. Study of project alternatives, energy renovation and selection of project and works management.",
  },

  {
    ref: "DA0010",
    short: "GCZ",
    title: "Gran Cafe Zaragoza",
    categoria: "heritage",
    location: "Zaragoza",
    superficie: 180,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Carmen Sisquella"],
    fotografia: "",
    orden: 4,
    año: 2000,
    images: [gcz1, gcz2, gcz3, gcz4, gcz5],
    description:
      "Reform of the emblematic establishment on calle Alfonso I in Zaragoza, the work of the local architect Luís Aladrén in 1885, with an eclectic and historicist style typical of the late s. XIX. The original business with a large corner façade was used as a famous jewelry store for the new bourgeoisie of the city. The glass-enclosed display cases and coffered ceilings inside conveyed the luxury of the silver and jewelry trade. The project transformed the commercial use to that of the new property “Gran Café Zaragoza” which would later remain as “Café 1885”. The interior rooms are cleaned of curtains, giving greater prominence to the cast iron columns and the elaborate coffered ceilings. Local declared Well Cataloged of the Aragonese Cultural Heritage by the Government of Aragon since 2002.",
  },
  {
    ref: "DA0569",
    short: "STA MARIA",
    title: "Santa Maria 33",
    categoria: "heritage",
    location: "Sant Cugat del Vallès ( Barcelona)",
    superficie: 165,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Carmen Sisquella"],
    fotografia: "",
    orden: 3,
    año: 2017,
    images: [sm1, sm2, sm3, sm4],
    description:
      "Performance in a small building of historical value in the old town of Sant Cugat del Vallés. The abandoned traditional house is updated to the new use in the main commercial street of the municipality, maintaining the use of housing on the first floor. The main façade, the traditional “volta” structure and the roof eaves are recovered and valued. Capillarity damp and attacks on the roof structure by termites and damp are also treated and eliminated. Building declared BCIL (Cultural Asset of Local Interest).",
  },
  {
    ref: "DA0573",
    short: "UVIC-CAMPUS",
    title: "Uvic Campus Casa Convalescencia",
    categoria: "heritage",
    location: "Vic ( Barcelona)",
    superficie: 4050,
    promotor: "Universitat de Vic",
    equipo: ["D'Aura Arquitectura", "Vives-Bassa-Ayala SCP"],
    fotografia: "",
    orden: 2,
    año: null,
    images: [
      campus1,
      campus10,
      campus11,
      campus2,
      campus3,
      campus4,
      campus5,
      campus6,
      campus7,
      campus8,
      campus9,
    ],
    description:
      "Restoration of the old Convalescence Home of the Hospital de la Santa Creu de Vic, the work of the architect Josep Morató i Codina, built halfway between Baroque (late 18th century) and Neoclassicism (early 19th century). It is an action in 4000 m2 of building, including, located on the edge of the old medieval wall of Vic. The objective of the action is to reuse the building as the headquarters of the Rectorate of the University of Vic and a retail and shopping center -working, Creacció. The University of Vic, the Vic City Council and the Board of Trustees of the Hospital de la Santa Creu, as the owner of the building, have been involved in the process during the almost 14 years that the entire intervention has lasted. The building was in a poor state of conservation, but it presented a constructive richness and high-quality architectural spaces, including a neoclassical cloister, 24 baroque vaults and high-quality paintings. The cloister and all the circulations around it have been recovered. The restorative spirit has led us to recover or repair the well-preserved existing carpentry, improving thermal behavior. Most of the wooden structures and the 24 existing vaults have also been preserved, repairing or reinforcing. After the Restoration the Building has been declared BCIL (Cultural Asset of Local Interest).",
  },
  {
    ref: "DA0621",
    short: "PARANINF",
    title: "Antigua Esglesia de la Santa Creu de Vic y Sala Gótica-Paraninf",
    categoria: "heritage",
    location: "Vic ( Barcelona)",
    superficie: 4050,
    promotor: "Universitat de Vic",
    equipo: ["D'Aura Arquitectura", "Vives-Bassa-Ayala SCP"],
    fotografia: "",
    orden: 1,
    año: null,
    images: [iglesia1, iglesia2, iglesia3, iglesia4, iglesia5, iglesia6],
    description:
      "The Iglesia de la Santa Creu, the work of Josep Morató i Sellés, was built between 1748 and 1753. It is a unique nave of imposing architectural volumetry, especially highlighting the cambril, splendidly ornamented. The interior pictorial decoration has been restored in different historical stages, with greater and lesser success, finally leaving an ornate style. The entire architectural complex is baroque and neoclassical transition. A room attached to the church of Gothic origin with large pointed arches originally belonging to the Hospital de la Santa Creu is restored and incorporated into the use of the auditorium. This comprehensive restoration has made it possible to recover and value the work of a whole saga of very important artists and master builders from a historical period in Catalonia, between the 17th and 18th centuries: the Morató nisaga vigatana. Building declared BCIL (Cultural Asset of Local Interest).",
  },
  {
    ref: "DA0722",
    short: "FJB",
    title: "Casa Francesc Lalanne",
    categoria: "heritage",
    location: "Barcelona",
    superficie: null,
    promotor: "Fundació Jaume Bofill",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "",
    orden: 3,
    año: null,
    images: [
      lalanne1,
      lalanne2,
      lalanne3,
      lalanne4,
      lalanne5,
      lalanne6,
      lalanne7,
      lalanne8,
      lalanne9,
      lalanne10,
    ],
    description:
      "Set of performances at the Casa Francesc Lalanne, also known as Casas Armentera i Parellada, in the Eixample district of Barcelona. Intervention was made in this 1908-1910 building, recovering historical elements hidden by previous interventions, carrying out a detailed structural analysis, and adapting the spaces to the new needs of the Foundation that owns the building. The valorization of the brick vaults and the pavements of Nolla put the building designed by the architect of ls. XIX-XX Arnau Calvet. 1st Prize Project Competition. Building declared BCIL (Cultural Asset of Local Interest).",
  },
  {
    ref: "DA0804",
    short: "ARTRUTX",
    title: "Talaia D'Artrutx",
    categoria: "heritage",
    location: "Ciutadella de Menorca ( Balears)",
    superficie: 115,
    promotor: "",
    equipo: [],
    fotografia: "",
    orden: 5,
    año: null,
    images: [artrux1, artrux2, artrux3, artrux4, artrux5],
    description:
      "The 'Talaias' are interesting observation towers strategically located around the Menorcan coast. La Talaia de Artruts is located on the southwest coast of Menorca and dates from the late 16th century to the early 17th century. It is an Asset of Cultural Interest (BIC) identified in the Ciutadella Historical Heritage Protection Catalog. The project consolidates the building with local and traditional materials and recovers eliminated elements. The action will allow to avoid the progressive deterioration and the future visit of the building.",
  },
  {
    ref: "DA0015",
    short: "LA FRASCA",
    title: "Bodega R. Lopez de Heredia",
    categoria: "architecture",
    location: "Haro (La Rioja)",
    superficie: 680,
    promotor: "R. López de Heredia",
    equipo: ["D'Aura Aquitectura", "Zaha Hadid Architects", "IOA"],
    fotografia: "",
    orden: 2,
    año: 2006,
    images: [blh1, blh2, blh3, blh4, blh5, blh6, blh7],
    description:
      "Tasting rooms, reception patio and visitor service building at Bodegas R. López de Heredia. As local architects, in collaboration with Zaha Hadid Arch., we have experimented with the design of architectural spaces, innovative structural solutions and new materials, which serve as a reference for the renovation of a century-old family winery. The result has added new values related to the traditional culture of 'Viña Tondonia'. The reception building houses the exhibition pavilion that Viña Tondonia showed at the 1910 fair. The new modular container was initially conceived to participate in new fairs, and, finally, it stands as an access point for visitors from the cellar Both 'La Frasca', as well as the exterior spaces, the new access to the winery or the tasting rooms incorporate technologically innovative solutions to provide the visitor with a new approach to the winery, the wine experience and its landscapes.",
  },
  {
    ref: "DA0118",
    short: "VTDN",
    title: "Viña Tondonia Stand",
    categoria: "architecture",
    location: "Barcelona",
    superficie: 680,
    promotor: "R. López de Heredia",
    equipo: ["D'Aura Aquitectura", "IOA"],
    fotografia: "Marcela Grassi",
    orden: 4,
    año: null,
    images: [vts1, vts2, vts3, vts4, vts5, vts6, vts7],
    description:
      "Ephemeral architecture for the brand image of the Winery in international events. The small-sized project includes the exhibition of the brand, its products, and space for visitor service and product tasting. The graphic image of the century-old winery and the characteristic old gold color of its Gran Reserva wine take center stage in an intimate and singular stand. The organic forms accompany the visitor towards the vineyards of the Rioja Alta and the underground galleries next to the Ebro river.",
  },
  {
    ref: "DA0138",
    short: "VIENESOS",
    title: "Centre Cívic els Vienesos",
    categoria: "architecture",
    location: "El Masnou (Barcelona)",
    superficie: null,
    promotor: "Ajuntament El Masnou",
    equipo: ["D'Aura Aquitectura", "IOA"],
    fotografia: "",
    orden: 6,
    año: null,
    images: [ccev1, ccev2, ccev3],
    description:
      "Expansion of the 'Els Vienesos' Civic Center with new multipurpose rooms, classrooms and a new floor. The project unifies the existing spaces and those resulting from the extension, giving a new urban and significant façade to the adjacent pedestrian space.",
  },
  {
    ref: "DA0470",
    short: "CA LA MINA",
    title: "Centre Cívic CA La Mina",
    categoria: "architecture",
    location: "Montcada i Rexac (Barcelona)",
    superficie: 1200,
    promotor: "Ajuntament Montcada i Rexac",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 7,
    año: null,
    images: [mina1, mina2, mina3, mina4],
    description:
      "Enlargement of the “Parc de les Aigües” Civic Center. The main objective of this project was to find a creative and efficient way to enlarge the existing civic center. This Center is built on the historic Montcada i Reixac water mine, which feeds the 'Rec Comtal' from a Roman waterway parallel to the Besós river. Therefore, the project had to grow vertically and it was resolved with the creation of a new floor on the existing roof, which visually opened the building up to the natural environment that surrounds it. A new entrance is also proposed from the rear of the building, the street that connects downtown Montcada with the Can Sant Joan neighborhood. The extension was built with prefabricated lightweight components that connect the existing building with the new building.",
  },
  {
    ref: "DA0523",
    short: "BOARDRIDERS",
    title: "Boardriders Barceloneta",
    categoria: "architecture",
    location: "Barcelona",
    superficie: 290,
    promotor: "",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "",
    orden: null,
    año: null,
    images: [
      boardriders1,
      boardriders2,
      boardriders3,
      boardriders4,
      boardriders5,
    ],
    description:
      "Conversion of an industrial building on the seafront of Barcelona. The transformation of an old industrial space and its opening to the new seafront led to the appearance of dysfunctional spaces without urban fit. The intervention in these spaces must allow the arrival of new uses, their updating, and a new integration in the transformed urban space. With these premises, the project maintains the character of the existing spaces, recovering structures and materials, but incorporating the urban leisure and commercial activities that have colonized the seafront.",
  },
  {
    ref: "DA0628",
    short: "CORUS",
    title: "Corus Laboratories",
    categoria: "architecture",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: 685,
    promotor: "Corus Dental Institute",
    equipo: ["D'Aura Arquitectura", "Ferran Arquitectura"],
    fotografia: "Marcela Grassi",
    orden: 2,
    año: null,
    images: [corus1, corus2, corus3, corus4, corus5, corus6],
    description:
      "Heaquarters and laboratories of a healthcare multinational in Spain. The production processes of the new laboratories are the main reason for the project. Different degrees of transparency are used in the sectorization of the spaces to show and relate activities. The circulation of materials and information define distributions, materials and common spaces. The work with the different departments of the company makes the building also a corporate image and positioning in its sector.",
  },
  {
    ref: "DA0681",
    short: "BIB SCG",
    title: "Biblioteca Central Sant Cugat",
    categoria: "architecture",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: null,
    promotor: "Ajuntament de Sant Cugat",
    equipo: ["D'Aura Arquitectura", "Arturo Frediani"],
    fotografia: "",
    orden: 2,
    año: 2017,
    images: [cugat1, cugat2, cugat3, cugat4, cugat5, cugat6, cugat7],
    description:
      "New building for the Gabriel Ferrater Library in the Ramon Barnils park in Sant Cugat del Vallès. 3rd prize project competition. The project emerges from the landscape like a nameless and timeless old fortress. We imagine the library as an enveloping shelter of books, a building full of luminous, solitary or collective corners, where one can find both the calm of reading and the stimulation of meeting and exchanging ideas. The interior spaces are not rectangular, but polygons with 5 or 6 sides. Thus, with the shelves we can create spaces that surround the reader without restricting their movements, and increasing storage capacity by up to 50%. The park is part of the building and the park building, related to the interior and exterior spaces. The roofs blend visually with the park and, due to their staggering, reveal the distant view of the Monastery of Sant Cugat, so present in the municipality, and with whom the library will keep a formal and conceptual resonance. Contemporary is compatible with Historical.",
  },
  {
    ref: "DA0729",
    short: "OASIS",
    title: "Hotel Oasis",
    categoria: "architecture",
    location: "Marbella (Málaga)",
    superficie: 650,
    promotor: "Selenta Group",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: 2020,
    images: [oasis1, oasis2, oasis3, oasis4],
    description:
      "Water area and lounge bar for the Hotel Oasis (Marbella). Natural materials and vegetation characterize the project to create a relaxing space that is different from the rest of the hotel's activities. The pool is a social space next to the lounge bar that opens or closes to it according to the schedules and scheduled activities. Water is one more element of the garden's landscaping project, incorporating the nearby nature and the more distant nature of the Sierra Blanca.",
  },
  {
    ref: "DA0603",
    short: "WBF",
    title: "World Basket Festival",
    categoria: "sport",
    location: "Barcelona",
    superficie: 2500,
    promotor: "Nike",
    equipo: [],
    fotografia: "Marcela Grassi",
    orden: 3,
    año: null,
    images: [wbf1, wbf2, wbf3, wbf4, wbf5],
    description:
      "Sports facility on the occasion of the Barcelona Basketball World Cup. Beyond the professional competition of a Basketball World Cup, urban sport is a leisure and socializing activity. This facility combines spaces for physical activity and competition, with sports and music shows, and leisure areas. Despite its short duration, its urban impact has attracted more than 30,000 visitors. All the elements of the installation are of light construction and reusable for new events.",
  },
  {
    ref: "DA0691",
    short: "WP'18",
    title: "Waterpolo BCN'18 Campeonato de Europa",
    categoria: "sport",
    location: "Barcelona",
    superficie: 2480,
    promotor: "Federeació Catalana de Natació",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [water1, water2, water3, water4, water5, water6],
    description:
      "Reform of the Bernat Picornell swimming pools to host the 33rd Barcelona2018 Water Polo European Championship. A new outdoor pool space is projected, configuring stands for 3,700 spectators, a large pergola, stage and projection screens around the sheet of water to create a unique and memorable space for this sporting event. The changing rooms and annex spaces are reformed and redistributed to house sports teams, competition management technicians and televisions. The exterior spaces are adapted to accommodate the Village, public spaces and the exterior image of the event.",
  },
  {
    ref: "DA0695",
    short: "C.N. OLOT",
    title: "C.N. OLOT",
    categoria: "sport",
    location: "Olot (Girona)",
    superficie: 3200,
    promotor: "C.N. Olot",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [olot1, olot2, olot3],
    description:
      "Rehabilitation and expansion project of the sports facilities of the Club Natació Olot. The intervention on the existing equipment preserves the functional spaces and creates a new enclosure and roof structure for the main pool. The exterior spaces are related to the interior activity, allowing a more permeable use in summer.",
  },
  {
    ref: "DA0714",
    short: "MIRASOL",
    title: "Piscina Municipal Mirasol",
    categoria: "sport",
    location: "Sant Cugat del Vallès (Barcelona)",
    superficie: null,
    promotor: "Ajuntament Sant Cugat",
    equipo: [],
    fotografia: "",
    orden: 7,
    año: null,
    images: [mirasol1, mirasol2, mirasol3],
    description:
      "The building is located on the designated plot, looking for an easy and natural settlement on the ground and detaches slightly to connect its surroundings. The aim is to create an attractive and compact volume that integrates with the building and the surrounding environment. The proposal differentiates the spaces for sports practice, the pool room and other rooms, giving them a preferential and representative character. The rest of the spaces are organized in longitudinal program strips or packages, consistent with the circulation schemes typical of sports facilities 3rd prize Project Competition.",
  },
  {
    ref: "DA0720",
    short: "FWS-21",
    title: "Fina Artistic Swimming World Series 2021",
    categoria: "sport",
    location: "Barcelona",
    superficie: 1500,
    promotor: "Federació Catalana Natació",
    equipo: [],
    fotografia: "",
    orden: 8,
    año: null,
    images: [sws1, sws2, sws3, sws4],
    description:
      "Ephemeral architecture for the celebration in Barcelona of the World Series 2021 of Artistic Swimming and the Olympic Qualification Tournament for Tokyo 2021 Transformation of sports equipment to adapt it to the regulatory needs of the competition and the architectural needs of the spectators and the broadcasts of the show. Study of the environments, lighting and different uses of the sheet of water and adjacent settings to create a global image recognizable to the viewer.",
  },
  {
    ref: "DA0733",
    short: "50'S",
    title: "Fluidra 50'S Anniversary",
    categoria: "sport",
    location: "Barcelona",
    superficie: 1500,
    promotor: "Fluidra",
    equipo: ["D'Aura Arquitectura", "Franc Aleu", "Fluidra Engineering"],
    fotografia: "",
    orden: 6,
    año: null,
    images: [fluidra1, fluidra2, fluidra3, fluidra4, fluidra5],
    description:
      "Research project with a wonderful team for the creation of an audiovisual show in the water. The show with a powerful audiovisual narrative takes place above and below the surface of the water, using this element with its maximum expressiveness, thanks to the use of fountains, platforms and lighting that enhance the choreography of swimmers and dancers. Creation of new technical elements such as the central platform used as a stage and a water, light and sound projector.",
  },
  {
    ref: "DA0745",
    short: "CNT",
    title: "Club Natació Terrassa",
    categoria: "sport",
    location: "Terrassa (Barcelona)",
    superficie: 3220,
    promotor: "Club Natació Terrassa",
    equipo: [],
    fotografia: "",
    orden: 6,
    año: null,
    images: [terrassa1, terrassa2, terrassa3, terrassa4],
    description:
      "Training and competition pool at Club Natació Terrassa. The project provides the installation of a new pool for sports activities, convertible into two water polo competition pools by means of a mobile bridge. The new construction is inserted between the existing ones, proposing a compact and efficient solution. The volume recalls the industrial past of the area but with the lightness of the current prefabricated construction systems. The natural light and the control of the views define the proportion of openings and spaces, and the relationship with the rest of the volumes.",
  },
  {
    ref: "DA0758",
    short: "CNG",
    title: "Club Natació Granollers",
    categoria: "sport",
    location: "Granollers (Barcelona)",
    superficie: 3590,
    promotor: "Ajuntament Granollers",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [gran1, gran2, gran3],
    description:
      "Training and competition pool at Club Natació Terrassa. The project provides the facility with a new pool for sports activities, convertible into two water polo competition pools by means of a mobile bridge. The new construction is inserted between the existing ones, proposing a compact and efficient solution. The volume recalls the industrial past of the area but with the lightness of the current prefabricated construction systems. The natural light and the control of the views define the proportion of openings and spaces, and the relationship with the rest of the volumes.",
  },
  {
    ref: "DA0759",
    short: "CARTAMA",
    title: "Complejo Acuático de la Ciudad Deportiva de Cártama",
    categoria: "sport",
    location: "Cártama (Málaga)",
    superficie: null,
    promotor: "Ayuntamiento de Cártama",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [cartama1, cartama2, cartama3, cartama4, cartama5, cartama6],
    description:
      "Sports equipment with indoor pool and attached multipurpose spaces. 1st Prize Project Competition. The project proposes an installation that defends the urban scale of the complex. The sports space as an infrastructure that in this case articulates the connection between the two urban centers of the municipality. On an intermediate scale, the water area building intervenes in the organization of the Sports City, redefining the accesses and the centrality of the spaces. On the smallest scale, the project proposes a compact building with high energy efficiency; user-oriented and sustainable management.",
  },
  {
    ref: "DA0802",
    short: "CAN RABASSA",
    title: "Piscina Municipal Can Rabassa",
    categoria: "sport",
    location: "Vilanova del Vallès (Barcelona)",
    superficie: 1200,
    promotor: "Ajuntament Vilanova del Vallès",
    equipo: [],
    fotografia: "",
    orden: 2,
    año: null,
    images: [can1, can2, can3, can4],
    description:
      "Municipal sports and leisure equipment. 1st prize contest. The new leisure and sports complex is located next to Masía Can Rabassa, improving its features and highlighting its history and the surrounding natural spaces. Drafting of a master plan for the complex, anticipating future growth and expansion of activities, as well as its connection with the Serralada Litoral Natural Park. The equipment consists of a mixed pool (leisure / education), natural and leisure areas, and a light service building.",
  },
];

const colors = {
  all: "#DF6537",
  architecture: "#203457",
  sport: "#7F9052",
  heritage: "#7F403B",
  "real estate": "#CBA971",
};


export { proyectosEN, colors };
